# Generated by Django 2.1.1 on 2018-11-14 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0002_person_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('cover', models.FileField(null=True, upload_to='book_covers/%Y/%m/%d')),
                ('author', models.CharField(max_length=200)),
                ('Issued_on', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbvapp.person')),
            ],
        ),
    ]
